# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2361be02fd157f41c28a6cd575dd1a0563d502868d2405f605c6a3b022da94b8bc14ea9c9d0274253351b0c1b59350bda46037cd95992535e93024e471b652d0

test:
  secret_key_base: cdc7941230b4de4aeb17c5b9a57172d6f87d282538634c61019e0ef1bb70c6fdb79dab929502d1e65bcbcea311fad556ce4ef885735d4e7129ecfef75d45fb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
